force-app/main/default/objects/Product2/fields/PT_codProducto__c.field-meta.xml
<CustomField>
    <fullName>PT_codProducto__c</fullName>
    <externalId>true</externalId>
    <label>Código Producto</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PT_almacenes__c/PT_almacenes__c.object-meta.xml
<CustomObject>
    <label>Almacen</label>
    <nameField>
        <label>Almacen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Almacenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PT_almacenes__c/fields/PT_almacenDestino__c.field-meta.xml
<CustomField>
    <fullName>PT_almacenDestino__c</fullName>
    <label>Almacen Destino</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCN</fullName>
                <label>Barcelona</label>
            </value>
            <value>
                <fullName>MAD</fullName>
                <label>Madrid</label>
            </value>
            <value>
                <fullName>SEV</fullName>
                <label>Sevilla</label>
            </value>
            <value>
                <fullName>VLN</fullName>
                <label>Valencia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PT_almacenes__c/fields/PT_cantidad__c.field-meta.xml
<CustomField>
    <fullName>PT_cantidad__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PT_almacenes__c/fields/PT_codProducto__c.field-meta.xml
<CustomField>
    <fullName>PT_codProducto__c</fullName>
    <label>Código Producto</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PT_almacenes__c/fields/PT_fechaEnvio__c.field-meta.xml
<CustomField>
    <fullName>PT_fechaEnvio__c</fullName>
    <label>Fecha Envío</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PT_almacenes__c/fields/PT_producto__c.field-meta.xml
<CustomField>
    <fullName>PT_producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Almacenes</relationshipLabel>
    <relationshipName>Almacenes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PT_productoProvisional__c/PT_productoProvisional__c.object-meta.xml
<CustomObject>
    <label>Producto Provisional</label>
    <nameField>
        <label>Producto Provisional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos Provisionales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PT_productoProvisional__c/fields/PT_cantidad__c.field-meta.xml
<CustomField>
    <fullName>PT_cantidad__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PT_productoProvisional__c/fields/PT_descripcion__c.field-meta.xml
<CustomField>
    <fullName>PT_descripcion__c</fullName>
    <label>Descripcion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PT_productoProvisional__c/fields/PT_producto__c.field-meta.xml
<CustomField>
    <fullName>PT_producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Productos Provisionales</relationshipLabel>
    <relationshipName>Productos_Provisionales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PT_insertarProductoAlmacen.cls
/**
 * @description       : CLASE QUE INSERTA LOS PRODUCTOS EN EL ALMACÉN UNA VEZ APROBADOS.
 * @author            : IULIAN PREDA VLASCEANU
 * @group             : 
 * @last modified on  : 26-05-2023
 * @last modified by  : IULIAN PREDA VLASCEANU
 * Modifications Log
 * Ver   Date         Author                   Modification
 * 1.0   26-05-2023   IULIAN PREDA VLASCEANU   Initial Version
**/
public with sharing class PT_insertarProductoAlmacen{
    public void insertProductosAlmacen(Map<String, PT_productoProvisional__c> mapProductosAlmacen){

        Map<String, PT_almacenes__c> mapProductosAInsertar = new Map<String, PT_almacenes__c>();
        Map<String, Product2> mapProductoParent = new Map<String, Product2>();

        for (Product2 productoParent : [SELECT Id, PT_codProducto__c, Description, Name
                                        FROM Product2
                                        WHERE PT_codProducto__c IN:mapProductosAlmacen.keyset()]){
            mapProductoParent.put(productoParent.PT_codProducto__c, productoParent);
        }

        for (String key : mapProductosAlmacen.keySet()){

            PT_almacenes__c altaProductoAlmacen = new PT_almacenes__c();
            altaProductoAlmacen.PT_producto__c = mapProductoParent.get(key).Id;
            altaProductoAlmacen.PT_fechaEnvio__c = Date.valueOf(mapProductosAlmacen.get(key).PT_fechaEnvio__c);
            altaProductoAlmacen.PT_codProducto__c = mapProductoParent.get(key).PT_codProducto__c;
            altaProductoAlmacen.PT_descripcion__c = mapProductoParent.get(key).Description;
            altaProductoAlmacen.PT_cantidad__c = Integer.ValueOf(mapProductosAlmacen.get(key).PT_cantidad__c);
            altaProductoAlmacen.PT_almacenDestino__c = mapProductosAlmacen.get(key).PT_almacenDestino__c;
            altaProductoAlmacen.Name = mapProductoParent.get(key).Name;
            mapProductosAInsertar.put(key, altaProductoAlmacen);

        }
        insert mapProductosAInsertar.values();
    } 

}